// src/pages/Search.tsx

import React, { useState } from "react";
import { Search } from "lucide-react";
import { useMovieSearch } from "../services/movieApi";
import MovieCard from "../components/MovieCard";

const SearchPage = () => {
  const [inputValue, setInputValue] = useState("");
  const { movies, loading, error, totalResults, setQuery, page, setPage } = useMovieSearch();

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setQuery(inputValue);
  };

  const totalPages = Math.ceil(totalResults / 10);

  return (
    <div className="py-6 animate-fade-in">
      <h1 className="text-3xl font-bold mb-6 text-center">Search Movies</h1>

      <form onSubmit={handleSearch} className="max-w-2xl mx-auto mb-8">
        <div className="relative">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            placeholder="Search for movies, TV shows, or episodes..."
            className="w-full bg-secondary/50 border border-white/10 rounded-full py-3 px-6 pr-12 focus:outline-none focus:ring-2 focus:ring-primary/50"
          />
          <button
            type="submit"
            className="absolute right-2 top-1/2 -translate-y-1/2 bg-primary text-white p-2 rounded-full hover:bg-primary/80 transition-colors"
            aria-label="Search"
          >
            <Search size={20} />
          </button>
        </div>
      </form>

      {loading && (
        <div className="flex justify-center my-12">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
        </div>
      )}

      {error && !loading && (
        <div className="text-center my-12 text-white/80">
          <p>{error}</p>
        </div>
      )}

      {!loading && !error && movies.length > 0 && (
        <>
          <p className="text-white/70 mb-4 text-center">
            Found {totalResults} results
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {movies.map((movie) => (
              <MovieCard key={movie.imdbID} movie={movie} />
            ))}
          </div>

          {totalPages > 1 && (
            <div className="flex justify-center mt-8 gap-2">
              <button
                onClick={() => setPage(page - 1)}
                disabled={page === 1}
                className="px-4 py-2 rounded-md bg-secondary hover:bg-secondary/80 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Previous
              </button>
              <span className="px-4 py-2">
                Page {page} of {totalPages}
              </span>
              <button
                onClick={() => setPage(page + 1)}
                disabled={page >= totalPages}
                className="px-4 py-2 rounded-md bg-secondary hover:bg-secondary/80 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Next
              </button>
            </div>
          )}
        </>
      )}

      {!loading && !error && inputValue === "" && (
        <div className="text-center my-12 text-white/80">
          <p>Enter a search term to find movies</p>
        </div>
      )}
    </div>
  );
};

export default SearchPage;

// src/app/pages/search/search.component.ts

import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { debounceTime, distinctUntilChanged, switchMap, tap } from 'rxjs/operators';
import { Movie } from '../../models/movie.model';
import { MovieService } from '../../services/movie.service';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {
  searchControl = new FormControl('');
  movies: Movie[] = [];
  loading = false;
  error = '';
  totalResults = 0;
  currentPage = 1;
  
  constructor(private movieService: MovieService) {}
  
  ngOnInit(): void {
    this.searchControl.valueChanges.pipe(
      debounceTime(400),
      distinctUntilChanged(),
      tap(() => {
        this.currentPage = 1;
        this.loading = true;
      }),
      switchMap(query => this.movieService.searchMovies(query || '', this.currentPage))
    ).subscribe({
      next: (result) => {
        this.movies = result.movies;
        this.totalResults = result.totalResults;
        this.loading = false;
        this.error = '';
      },
      error: (err) => {
        this.error = err.message || 'Failed to fetch movies';
        this.loading = false;
        this.movies = [];
        this.totalResults = 0;
      }
    });
  }
  
  search(): void {
    this.loading = true;
    this.movieService.searchMovies(this.searchControl.value || '', this.currentPage)
      .subscribe({
        next: (result) => {
          this.movies = result.movies;
          this.totalResults = result.totalResults;
          this.loading = false;
          this.error = '';
        },
        error: (err) => {
          this.error = err.message || 'Failed to fetch movies';
          this.loading = false;
          this.movies = [];
          this.totalResults = 0;
        }
      });
  }
  
  changePage(newPage: number): void {
    if (newPage < 1 || newPage > this.totalPages) return;
    
    this.currentPage = newPage;
    this.search();
  }
  
  get totalPages(): number {
    return Math.ceil(this.totalResults / 10);
  }
}


<div class="py-6 animate-fade-in">
  <h1 class="text-3xl font-bold mb-6 text-center">Search Movies</h1>

  <form (ngSubmit)="search()" class="max-w-2xl mx-auto mb-8">
    <div class="relative">
      <input
        type="text"
        [formControl]="searchControl"
        placeholder="Search for movies, TV shows, or episodes..."
        class="w-full bg-secondary/50 border border-white/10 rounded-full py-3 px-6 pr-12 focus:outline-none focus:ring-2 focus:ring-primary/50"
      />
      <button
        type="submit"
        class="absolute right-2 top-1/2 -translate-y-1/2 bg-primary text-white p-2 rounded-full hover:bg-primary/80 transition-colors"
        aria-label="Search"
      >
        <i class="lucide lucide-search" style="width: 20px; height: 20px;"></i>
      </button>
    </div>
  </form>

  <div *ngIf="loading" class="flex justify-center my-12">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
  </div>

  <div *ngIf="error && !loading" class="text-center my-12 text-white/80">
    <p>{{ error }}</p>
  </div>

  <ng-container *ngIf="!loading && !error && movies.length > 0">
    <p class="text-white/70 mb-4 text-center">
      Found {{ totalResults }} results
    </p>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
      <app-movie-card *ngFor="let movie of movies" [movie]="movie"></app-movie-card>
    </div>

    <div *ngIf="totalPages > 1" class="flex justify-center mt-8 gap-2">
      <button
        (click)="changePage(currentPage - 1)"
        [disabled]="currentPage === 1"
        class="px-4 py-2 rounded-md bg-secondary hover:bg-secondary/80 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        Previous
      </button>
      <span class="px-4 py-2">
        Page {{ currentPage }} of {{ totalPages }}
      </span>
      <button
        (click)="changePage(currentPage + 1)"
        [disabled]="currentPage >= totalPages"
        class="px-4 py-2 rounded-md bg-secondary hover:bg-secondary/80 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        Next
      </button>
    </div>
  </ng-container>

  <div *ngIf="!loading && !error && searchControl.value === '' && movies.length === 0" class="text-center my-12 text-white/80">
    <p>Enter a search term to find movies</p>
  </div>
</div>
